{"name": "test_incorrect_username_and_password", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Wrong password.' == 'User does not exist.'\n  - User does not exist.\n  + Wrong password.", "trace": "self = <Web.Tests.test_login.Test_Login object at 0x000001C2A12E1F00>\n\n>   ???\nE   AssertionError: assert 'Wrong password.' == 'User does not exist.'\nE     - User does not exist.\nE     + Wrong password.\n\nC:\\Users\\user\\PycharmProjects\\Final Project\\Web\\Tests\\test_login.py:50: AssertionError"}, "description": "Verify login using the wrong username and password.", "steps": [{"name": "Opening the website", "status": "passed", "start": 1675537310129, "stop": 1675537310328}, {"name": "Clicking the element", "status": "passed", "parameters": [{"name": "locate", "value": "('xpath', \"//a[@id='login2']\")"}], "start": 1675537310328, "stop": 1675537310404}, {"name": "Clicking the element", "status": "passed", "parameters": [{"name": "locate", "value": "('xpath', \"//button[contains(text(),'Log in')]\")"}], "start": 1675537311170, "stop": 1675537311231}, {"name": "Read alert message", "status": "passed", "parameters": [{"name": "time", "value": "10"}], "start": 1675537311231, "stop": 1675537311758}], "start": 1675537310129, "stop": 1675537311758, "uuid": "22a11069-0c95-4f1e-8704-b6f20dc72aa8", "historyId": "04051d7f1e1ac2b37e0e1319cefe35c7", "testCaseId": "8483db41619fa1b90cf4612c81eaa890", "fullName": "Tests.test_login.Test_Login#test_incorrect_username_and_password", "labels": [{"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_Login"}, {"name": "host", "value": "mike"}, {"name": "thread", "value": "15340-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_login"}]}