{"name": "test_incorrect_username_and_password", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Wrong password.' == 'User does not exist.'\n  - User does not exist.\n  + Wrong password.", "trace": "self = <Web.Tests.test_login.Test_Login object at 0x000002E904219ED0>\n\n>   ???\nE   AssertionError: assert 'Wrong password.' == 'User does not exist.'\nE     - User does not exist.\nE     + Wrong password.\n\nC:\\Users\\user\\PycharmProjects\\Final Project\\Web\\Tests\\test_login.py:50: AssertionError"}, "description": "Verify login using the wrong username and password.", "steps": [{"name": "Opening the website", "status": "passed", "start": 1675538062156, "stop": 1675538062453}, {"name": "Clicking the element", "status": "passed", "parameters": [{"name": "locate", "value": "('xpath', \"//a[@id='login2']\")"}], "start": 1675538062453, "stop": 1675538062532}, {"name": "Clicking the element", "status": "passed", "parameters": [{"name": "locate", "value": "('xpath', \"//button[contains(text(),'Log in')]\")"}], "start": 1675538063282, "stop": 1675538063359}, {"name": "Read alert message", "status": "passed", "parameters": [{"name": "time", "value": "10"}], "start": 1675538063359, "stop": 1675538063881}], "start": 1675538062156, "stop": 1675538063882, "uuid": "53212f3a-1359-4a9a-936d-4a81c27ec3db", "historyId": "04051d7f1e1ac2b37e0e1319cefe35c7", "testCaseId": "8483db41619fa1b90cf4612c81eaa890", "fullName": "Tests.test_login.Test_Login#test_incorrect_username_and_password", "labels": [{"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_Login"}, {"name": "host", "value": "mike"}, {"name": "thread", "value": "7176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_login"}]}